### ISSUE TITLE
addAttrs is not defined

### ISSUE THREAD

**Issue by maksimenka** [gulp-bem/gulp-bem-xjst#74]
При сборке c помощью Gulp
`block('button').mod('type', 'link')(
    tag()('a'),
    addAttrs()({ id: 'test', name: 'test' })
);`

**Comment by qfox** [comment]
Дело в версии bem-xjst, в поставке какая-то 6.х, кажется

**Comment by maksimenka** [comment]
А возможно его обновить, очень много функций не работает? Или есть альтернатива использованию bem-xjst при сборке галпом?

**Comment by qfox** [comment]
Возможно, но нет библиотек, которые совместимы с 8.х, в которой есть addAttrs. Вы отдельно используете bem-xjst?

**Comment by maksimenka** [comment]
За основу брал: https://github.com/bem/project-stub
Но меня интересует только bem-xjst, т.е. я убрал bem-core и bem-components. Сборка в целом работает, просто начал описывать логику, и часть функций не работает которые описаны в документации.

**Comment by qfox** [comment]
Думаю что делать. Можно, конечно, топорно выпускать версии, но это надо делать вместе с релизами bem-xjst

cc @miripiruni

**Comment by maksimenka** [comment]
Мне по душе ваш шаблонизатор, но проблема в кадрах разбирающихся в i-bem и тд. Поэтому мы хотим использовать bem-xjst с фреймворком ангуляр. И возможно я не один такой.

**Comment by miripiruni** [comment]
@zxqfox а что тут думать? Нужно, чтобы ментейнер gulp-bem-xjst выпустил версии поддерживающие bem-xjst 7.x и 8.x

**Comment by miripiruni** [comment]
Можно настроить greenkeeper. Oh, wait… 39 пулреквестов… )

**Comment by qfox** [comment]
@miripiruni ну тогда нужно чтобы мейнтейнером этого пакета был ты)

**Comment by miripiruni** [comment]
@zxqfox я не могу поддерживать все метапакеты, которые есть в интернете. Ну то есть могу, но такие вещи нужно решать greenkeeper-ом.

**Comment by miripiruni** [comment]
@zxqfox не рассматриваешь вариант пустить поддерживать эти пакеты тех людей, которые действительно ими пользуются?

**Comment by miripiruni** [comment]
Я как бы намекаю на некоторых участников этого треда…

**Comment by maksimenka** [comment]
Как я понимаю @tadatuta, допилит ;)

**Comment by tadatuta** [comment]
Я с неделю назад заслал https://github.com/gulp-bem/gulp-bem-xjst/pull/69
Если мейнтейнера де-факто нет, то готов влить и выпустить версию.

@zxqfox, @blond даете добро?

**Comment by miripiruni** [comment]
Добавьте, пожалуйста, и меня в админы этого репозитория, я могу разово разобрать свалку из пулреквестов ближе к вечеру.

**Comment by tadatuta** [comment]
@miripiruni done

**Comment by miripiruni** [comment]
@tadatuta я всё ещё не могу управлять пулреквестами…

**Comment by maksimenka** [comment]
Когда ориентировочно ожидать мержа новой версии?

**Comment by miripiruni** [comment]
@tadatuta пинг?

**Comment by miripiruni** [comment]
@Maksimenka сегодня.

**Comment by maksimenka** [comment]
Ок, спасибо.

**Comment by miripiruni** [comment]
Выпустил 

gulp-bem-xjst@3.0.0 c зависимостью bem-xjst ^8.3.1
и gulp-bem-xjst@2.0.0 c зависимостью bem-xjst ^7.5.0
